# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pylims.models


class Migration(migrations.Migration):

    dependencies = [
        ('pylims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('text', models.TextField(blank=True)),
                ('digest', models.CharField(editable=False, max_length=128, unique=True)),
                ('args', pylims.models.TagsField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataImportDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_args', pylims.models.TagsField(blank=True)),
                ('python_code', pylims.models.PythonField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pylims.DataImportDriver')),
            ],
        ),
        migrations.CreateModel(
            name='DataImportTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=55)),
                ('value', models.TextField()),
                ('data_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pylims.DataImport')),
            ],
        ),
        migrations.AlterField(
            model_name='locationtag',
            name='key',
            field=models.SlugField(max_length=55),
        ),
        migrations.AlterField(
            model_name='parametertag',
            name='key',
            field=models.SlugField(max_length=55),
        ),
        migrations.AlterField(
            model_name='projecttag',
            name='key',
            field=models.SlugField(max_length=55),
        ),
        migrations.AlterField(
            model_name='sampletag',
            name='key',
            field=models.SlugField(max_length=55),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pylims.DataImportDriver'),
        ),
        migrations.AddField(
            model_name='location',
            name='data_import',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pylims.DataImport'),
        ),
        migrations.AddField(
            model_name='locationtag',
            name='data_import',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pylims.DataImport'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='data_import',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pylims.DataImport'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='data_import',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pylims.DataImport'),
        ),
        migrations.AddField(
            model_name='parametertag',
            name='data_import',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pylims.DataImport'),
        ),
        migrations.AddField(
            model_name='project',
            name='data_import',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pylims.DataImport'),
        ),
        migrations.AddField(
            model_name='projecttag',
            name='data_import',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pylims.DataImport'),
        ),
        migrations.AddField(
            model_name='sample',
            name='data_import',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pylims.DataImport'),
        ),
        migrations.AddField(
            model_name='sampletag',
            name='data_import',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pylims.DataImport'),
        ),
    ]
