# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pylims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pylims.Location'),
        ),
    ]
