# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pylims', '0003_auto_20171116_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimport',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pylims.DataImportDriver'),
        ),
    ]
