# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 00:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pylims', '0004_auto_20171116_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
